config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  resources :posts, only: [:new, :index, :create]
	get "posts/:id", to: redirect("/%{id}")
  resources :posts, path: '',except: [:new, :index, :create]

  devise_for :users

  resources :categories do
		resources :subcategories
	end
  get 'home/index'

  root 'home#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
	extend FriendlyId

	friendly_id :name, use: [:slugged, :history]

  belongs_to :user
  belongs_to :subcategory
  belongs_to :category

	def should_generate_new_friendly_id?
		name_changed?
	end

	has_attached_file :image, styles: { small: "64x64", med: "492", large: "200x200" }
	# validates_attachment :image
  # :content_type => { :content_type => "image/jpg" }
  # :size => { :in => 0..100.kilobytes }
	# has_attached_file :image
  # Validate content type
  validates_attachment_content_type :image, content_type: /\Aimage/
  # Validate filename
  # validates_attachment_file_name :image, matches: [/png\Z/, /jpe?g\Z/]
  # Explicitly do not validate
  # do_not_validate_attachment_file_type :image



end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
		if request.path != post_path(@post)
			return redirect_to @post, :status => :moved_permanently
		end
		@meta_title = @post.name
		@meta_description = @post.description

		# if @post.no_index?
		# 	no_index_no_follow
		# end
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
			@post = Post.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:name, :description, :counter, :user_id, :subcategory_id, :category_id, :image)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_disqus.html.erb
<div id="disqus_thread"></div>
<script>
/**
* RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
* LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables
*/
/*
var disqus_config = function () {
this.page.url = PAGE_URL; // Replace PAGE_URL with your page's canonical URL variable
this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable

};
*/






(function() { // DON'T EDIT BELOW THIS LINE
var d = document, s = d.createElement('script');

s.src = '//upotos.disqus.com/embed.js';

s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>

app/views/posts/_form.html.erb
<%= form_for(@post, html: { multipart: true }, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @post.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h4>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :image, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.file_field :image, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :description, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_area :description, class: "form-control ckeditor" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :counter, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :counter, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :subcategory_id, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
			<%= f.select :subcategory_id,Subcategory.all.map {|a| [a.name, a.id]}, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :category_id, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
			<%= f.select :category_id,Category.all.map {|a| [a.name, a.id]}, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/posts/edit.html.erb
<div class="page-header">
  <%= link_to posts_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @post, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing post</h1>
</div>

<%= render 'form' %>

app/views/posts/index.html.erb
<div class="page-header">
  <%= link_to new_post_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Post
  <% end %>
  <h1>Listing posts</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Name</th>
            <th>Image</th>
            <th>Description</th>
            <th>Counter</th>
            <th>User</th>
            <th>Subcategory</th>
            <th>Category</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @posts) do |post| %>
            <td><%= post.name %></td>
            <td><%= image_tag post.image %></td>
            <td><%= post.description %></td>
            <td><%= post.counter %></td>
            <td><%= post.user %></td>
            <td><%= post.subcategory %></td>
            <td><%= post.category %></td>
            <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/posts/new.html.erb
<div class="page-header">
  <%= link_to posts_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New post</h1>
</div>

<%= render 'form' %>

app/views/posts/show.html.erb
<div class="show-post">
	<h2 class='post-title' style="margin-bottom: 45px;"><%= @post.name %></h2>
	<div class="lineauto"></div>
	<div class="alignq">
		<span class="bg-date">
			<span class="post-category"><%= @post.subcategory.name if @post.subcategory %></span>
			<span class="dot-sep">·</span>
			<span class="post-category"><%= @post.created_at.strftime("%b %d, %Y") %></span>
		</span>
	</div>
		<%= image_tag @post.image %>
	<div class="container-fluid show-desc" style="margin-top:20px;">
		<p>
			<%= @post.description.html_safe %>
			<div style="margin-top:40px;">
				<%= render 'disqus' %>
			</div>
		</p>
	</div>
</div>